version: '3'

dotenv: ['backend/.env']

vars:
  MIGRATIONS_DIR: ./backend/migrations
  DATABASE_URL: 'postgresql://{{.POSTGRES_USER}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST}}:{{.POSTGRES_PORT}}/{{.POSTGRES_DB}}?sslmode=disable'

tasks:
  # Database migrations
  migrate:create:
    desc: "Create a new migration file"
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_DIR}} -seq {{.CLI_ARGS}}
    requires:
      vars: [CLI_ARGS]

  migrate:up:
    desc: "Apply all up migrations"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" up

  migrate:up:one:
    desc: "Apply one up migration"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" up 1

  migrate:down:
    desc: "Rollback all migrations"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" down
    prompt: This will rollback ALL migrations. Are you sure?

  migrate:down:one:
    desc: "Rollback one migration"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" down 1

  migrate:force:
    desc: "Force set migration version (use with caution)"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" force {{.CLI_ARGS}}
    requires:
      vars: [CLI_ARGS]

  migrate:version:
    desc: "Show current migration version"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" version

  migrate:drop:
    desc: "Drop everything in the database"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" drop
    prompt: This will drop EVERYTHING in the database. Are you sure?

  migrate:goto:
    desc: "Migrate to a specific version"
    cmds:
      - migrate -path {{.MIGRATIONS_DIR}} -database "{{.DATABASE_URL}}" goto {{.CLI_ARGS}}
    requires:
      vars: [CLI_ARGS]

  db:setup:
    desc: "Setup database (create migrations directory and apply all migrations)"
    cmds:
      - mkdir -p {{.MIGRATIONS_DIR}}
      - task: migrate:up

  db:reset:
    desc: "Reset database (drop all tables and re-apply migrations)"
    cmds:
      - task: migrate:drop
      - task: migrate:up
    prompt: This will reset the entire database. Are you sure?

  # Code generation
  api:generate:
    desc: "Generate API code from OpenAPI spec"
    dir: backend/api
    cmds:
      - oapi-codegen --config oapi-codegen.yaml swagger.yaml

  generate:
    desc: "Run all code generators"
    dir: backend
    cmds:
      - go generate ./...
      - task: api:generate

  # Backend tasks
  backend:build:
    desc: "Build the backend binary"
    dir: backend
    cmds:
      - go build -o bin/server ./cmd/server

  backend:run:
    desc: "Run the backend server"
    dir: backend
    cmds:
      - go run ./cmd/server

  backend:test:
    desc: "Run backend tests"
    dir: backend
    cmds:
      - go test ./...

  backend:test:verbose:
    desc: "Run backend tests with verbose output"
    dir: backend
    cmds:
      - go test -v ./...

  # Frontend tasks
  frontend:install:
    desc: "Install frontend dependencies"
    dir: frontend
    cmds:
      - npm install

  frontend:dev:
    desc: "Start frontend dev server"
    dir: frontend
    cmds:
      - npm run dev

  frontend:build:
    desc: "Build frontend for production"
    dir: frontend
    cmds:
      - npm run build

  frontend:preview:
    desc: "Preview production build"
    dir: frontend
    cmds:
      - npm run preview

  frontend:lint:
    desc: "Run frontend linter"
    dir: frontend
    cmds:
      - npm run lint

  frontend:typecheck:
    desc: "Run TypeScript type check"
    dir: frontend
    cmds:
      - npm run typecheck

  # Docker tasks
  docker:up:
    desc: "Start all services with docker-compose"
    cmds:
      - docker-compose up -d

  docker:down:
    desc: "Stop all services"
    cmds:
      - docker-compose down

  docker:build:
    desc: "Build all docker images"
    cmds:
      - docker-compose build

  docker:logs:
    desc: "View logs from all services"
    cmds:
      - docker-compose logs -f

  docker:logs:backend:
    desc: "View logs from backend service"
    cmds:
      - docker-compose logs -f backend

  docker:logs:frontend:
    desc: "View logs from frontend service"
    cmds:
      - docker-compose logs -f frontend
