// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package domain

import (
	"fmt"
	"strings"
)

const (
	// TransactionTypeTransfer is a TransactionType of type transfer.
	TransactionTypeTransfer TransactionType = "transfer"
	// TransactionTypeExchange is a TransactionType of type exchange.
	TransactionTypeExchange TransactionType = "exchange"
	// TransactionTypeDeposit is a TransactionType of type deposit.
	TransactionTypeDeposit TransactionType = "deposit"
	// TransactionTypeWithdrawal is a TransactionType of type withdrawal.
	TransactionTypeWithdrawal TransactionType = "withdrawal"
)

var ErrInvalidTransactionType = fmt.Errorf("not a valid TransactionType, try [%s]", strings.Join(_TransactionTypeNames, ", "))

var _TransactionTypeNames = []string{
	string(TransactionTypeTransfer),
	string(TransactionTypeExchange),
	string(TransactionTypeDeposit),
	string(TransactionTypeWithdrawal),
}

// TransactionTypeNames returns a list of possible string values of TransactionType.
func TransactionTypeNames() []string {
	tmp := make([]string, len(_TransactionTypeNames))
	copy(tmp, _TransactionTypeNames)
	return tmp
}

// TransactionTypeValues returns a list of the values for TransactionType
func TransactionTypeValues() []TransactionType {
	return []TransactionType{
		TransactionTypeTransfer,
		TransactionTypeExchange,
		TransactionTypeDeposit,
		TransactionTypeWithdrawal,
	}
}

// String implements the Stringer interface.
func (x TransactionType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TransactionType) IsValid() bool {
	_, err := ParseTransactionType(string(x))
	return err == nil
}

var _TransactionTypeValue = map[string]TransactionType{
	"transfer":   TransactionTypeTransfer,
	"exchange":   TransactionTypeExchange,
	"deposit":    TransactionTypeDeposit,
	"withdrawal": TransactionTypeWithdrawal,
}

// ParseTransactionType attempts to convert a string to a TransactionType.
func ParseTransactionType(name string) (TransactionType, error) {
	if x, ok := _TransactionTypeValue[name]; ok {
		return x, nil
	}
	return TransactionType(""), fmt.Errorf("%s is %w", name, ErrInvalidTransactionType)
}

// MarshalText implements the text marshaller method.
func (x TransactionType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TransactionType) UnmarshalText(text []byte) error {
	tmp, err := ParseTransactionType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *TransactionType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
